In [2]:
from functions import parameters as p
proj_param = p.Project_Parameters()

In [3]:
import pandas as pd

In [12]:
csi_path = proj_param.data_folder + "/crime_severity.parquet"
df_csi = pd.read_parquet(csi_path)
df_csi

Statistics,ref_date,geo,crime_severity_index,weighted_clearance_rate
0,1998,Alberta [48],122.50,40.89
1,1998,British Columbia [59],166.91,27.88
2,1998,"Calgary, Alberta [48825]",116.48,31.95
3,1998,Canada,118.84,34.06
4,1998,"Edmonton, Alberta [48835]",126.76,37.89
...,...,...,...,...
1222,2023,"Vancouver, British Columbia [59933]",90.23,17.36
1223,2023,"Victoria, British Columbia [59935]",79.91,22.48
1224,2023,"Windsor, Ontario [35559]",64.17,39.44
1225,2023,"Winnipeg, Manitoba [46602]",129.07,32.19
1226,2023,Yukon [60],218.76,36.38

In [13]:
ivd_path = proj_param.data_folder + "/incident_violation_detail.parquet"
df_ivd = pd.read_parquet(ivd_path)
df_ivd

Statistics,ref_date,geo,actual_incidents,total_cleared
0,1998,Alberta [48],7721.071429,3461.390476
1,1998,British Columbia [59],14002.576190,4570.180952
2,1998,"Calgary, Alberta [48825]",2049.161905,688.276190
3,1998,Canada,71693.071429,27514.547619
4,1998,"Edmonton, Alberta [48835]",2333.490476,1036.614286
...,...,...,...,...
1226,2023,"Vancouver, British Columbia [59933]",3396.804487,627.717949
1227,2023,"Victoria, British Columbia [59935]",472.884615,138.064103
1228,2023,"Windsor, Ontario [35559]",406.445513,139.333333
1229,2023,"Winnipeg, Manitoba [46602]",1355.951923,368.025641
1230,2023,Yukon [60],195.631410,75.108974

In [14]:
merged_data = pd.merge(df_csi, df_ivd, how = "outer" , on = ['ref_date','geo'])
merged_data

Statistics,ref_date,geo,crime_severity_index,weighted_clearance_rate,actual_incidents,total_cleared
0,1998,Alberta [48],122.50,40.89,7721.071429,3461.390476
1,1998,British Columbia [59],166.91,27.88,14002.576190,4570.180952
2,1998,"Calgary, Alberta [48825]",116.48,31.95,2049.161905,688.276190
3,1998,Canada,118.84,34.06,71693.071429,27514.547619
4,1998,"Edmonton, Alberta [48835]",126.76,37.89,2333.490476,1036.614286
...,...,...,...,...,...,...
1252,2023,"Vancouver, British Columbia [59933]",90.23,17.36,3396.804487,627.717949
1253,2023,"Victoria, British Columbia [59935]",79.91,22.48,472.884615,138.064103
1254,2023,"Windsor, Ontario [35559]",64.17,39.44,406.445513,139.333333
1255,2023,"Winnipeg, Manitoba [46602]",129.07,32.19,1355.951923,368.025641
1256,2023,Yukon [60],218.76,36.38,195.631410,75.108974

In [15]:
merged_data[merged_data['ref_date']==1998]

Statistics,ref_date,geo,crime_severity_index,weighted_clearance_rate,actual_incidents,total_cleared
0,1998,Alberta [48],122.50,40.89,7721.071429,3461.390476
1,1998,British Columbia [59],166.91,27.88,14002.576190,4570.180952
2,1998,"Calgary, Alberta [48825]",116.48,31.95,2049.161905,688.276190
3,1998,Canada,118.84,34.06,71693.071429,27514.547619
4,1998,"Edmonton, Alberta [48835]",126.76,37.89,2333.490476,1036.614286
5,1998,"Greater Sudbury, Ontario [35580]",107.43,30.42,333.800000,130.957143
6,1998,"Halifax, Nova Scotia [12205]",134.13,28.95,954.647619,277.042857
7,1998,"Hamilton, Ontario [35537]",100.94,30.03,1326.752381,507.861905
8,1998,"Kitchener-Cambridge-Waterloo, Ontario [35541]",100.61,30.84,841.528571,280.638095
9,1998,"London, Ontario [35555]",106.98,40.67,1095.709524,425.252381
10,1998,Manitoba [46],154.49,35.64,3483.257143,1351.014286
11,1998,"Montréal, Quebec [24462]",139.00,25.83,7297.085714,2034.285714
12,1998,New Brunswick [13],89.98,43.97,1528.261905,741.514286
13,1998,Newfoundland and Labrador [10],76.38,41.91,923.966667,419.676190
14,1998,Northwest Territories [61],267.47,54.16,442.966667,260.419048
15,1998,Nova Scotia [12],105.40,35.55,2205.157143,823.152381
16,1998,Ontario [35],100.72,35.79,23526.933333,9225.595238
17,1998,"Ottawa-Gatineau, Ontario part [35505]",113.82,27.67,1734.542857,535.800000
18,1998,"Ottawa-Gatineau, Ontario/Quebec [24505/35505]",111.15,29.16,2238.409524,749.452381
19,1998,"Ottawa-Gatineau, Quebec part [24505]",103.11,34.12,503.866667,213.652381
20,1998,Prince Edward Island [11],73.31,50.45,254.985714,129.280952
21,1998,Quebec [24],112.68,29.48,13541.957143,4544.009524
22,1998,"Québec, Quebec [24421]",91.05,31.92,1098.661905,388.666667
23,1998,"Regina, Saskatchewan [47705]",231.30,31.41,902.971429,341.638095
24,1998,"Saguenay, Quebec [24408]",114.09,26.52,320.271429,106.104762
25,1998,"Saint John, New Brunswick [13310]",101.24,41.93,286.885714,126.790476
26,1998,Saskatchewan [47],176.20,42.09,3893.228571,1903.371429
27,1998,"Saskatoon, Saskatchewan [47725]",179.13,33.68,787.752381,332.714286
28,1998,"Sherbrooke, Quebec [24433]",111.65,24.55,277.642857,87.185714
29,1998,"St. Catharines-Niagara, Ontario [35539]",NaN,NaN,894.319048,324.638095
30,1998,"St. John's, Newfoundland and Labrador [10001]",101.04,31.64,364.380952,124.452381
31,1998,"St.Catharines-Niagara, Ontario [35539]",107.97,34.94,NaN,NaN
32,1998,"Thunder Bay, Ontario [35595]",130.83,47.53,389.109524,210.985714
33,1998,"Toronto, Ontario [35535]",91.83,31.71,8116.528571,2832.690476
34,1998,"Trois-Rivières, Quebec [24442]",96.40,40.24,269.066667,126.428571
35,1998,"Vancouver, British Columbia [59933]",183.77,20.90,6859.076190,1640.476190
36,1998,"Victoria, British Columbia [59935]",145.45,36.84,1037.061905,393.480952
37,1998,"Windsor, Ontario [35559]",102.12,38.87,693.395238,271.133333
38,1998,"Winnipeg, Manitoba [46602]",160.21,29.94,1899.685714,582.176190
39,1998,Yukon [60],226.16,46.51,168.709524,84.942857

In [16]:
to_csv_path = proj_param.data_folder + "/merged_csi_ivd.csv"
merged_data.to_csv(to_csv_path)